spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/board
    username: sa
    password: 123
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create

